USE HARSHITH;

CREATE TABLE SCHOOL(ID INT,SCHOOL VARCHAR(20),STUDENT_NAME VARCHAR(20),GENDER VARCHAR(10)
   ,CLASS VARCHAR(10),AGE INT,FATHER_NAME VARCHAR(10),MOTHER_NAME VARCHAR(10));
   
   ALTER TABLE SCHOOL ADD COLUMN FATHER_OCCUPATION VARCHAR(10);
   ALTER TABLE SCHOOL ADD COLUMN MOTHER_OCCUPATION VARCHAR(10);
   
   CREATE TABLE MOVIE(ID INT,ACTOR VARCHAR(20), ACTRESS VARCHAR(20),MOVIE_NAME VARCHAR(20),
     DIRECTOR VARCHAR(20),PRODUCER VARCHAR(20),CAMERAMEN VARCHAR(20),MUSIC_DIRECTOR VARCHAR(20));
     
     ALTER TABLE MOVIE ADD COLUMN NO_OF_SONGS INT;
     ALTER TABLE MOVIE ADD COLUMN DISTRIBUTION VARCHAR(20);
     
     CREATE TABLE LAPTOP(ID INT,BRAND VARCHAR(10),MANUFACTURED_YEAR INT,RAM_IN_GB INT,
      DISPLAY_INCHES INT,OPERATING_SYSTEM VARCHAR(10),GENERATION VARCHAR(10),SDD_IN_GB INT);
      
      ALTER TABLE LAPTOP ADD COLUMN PRICE INT;
      ALTER TABLE LAPTOP ADD COLUMN USB_PORT INT;
      
      CREATE TABLE FITNESS(ID INT,GYM_NAME VARCHAR(20),CUSTOMER_NAME VARCHAR(20),AGE INT,
        GENDER VARCHAR(10),FESS INT,WEIGHT FLOAT,NO_OF_DAYS INT);
        
        ALTER TABLE FITNESS ADD COLUMN TRAINER_NAME VARCHAR(20); 
        ALTER TABLE FITNESS ADD COLUMN ADRESS VARCHAR(20);
        
        CREATE TABLE BIKE(ID INT,BRAND VARCHAR(10),MODEL_NAME VARCHAR(10),WEIGHT INT,
         MAX_SPEED INT,FUEL_TYPE VARCHAR(10), MANUFACTURED_YEAR INT,PRICE INT);
         
         ALTER TABLE BIKE ADD COLUMN REGISTRATION VARCHAR(20);
         ALTER TABLE BIKE ADD COLUMN ABS BOOLEAN;
         
   
   